server:
  port: 80
  error:
    whitelabel:
      enabled: false
      
spring:
  application:
    name: MultisBoardApplication
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  resources:
    add-mappings: false
  tomcat:
    uri-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.14/ multis_board?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwer1234
    hikari:
      maximum-pool-size: 5
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html   # 파일 확장자
    cache: false
    enabled: true